// !!        WARNING
// !! DO NOT EDIT THIS FILE
//
// This file is generated by the openapi-generator module and is not meant for manual changes.
// Please read the README.md file in the openapi-generator module for additional information.
@file:UseSerializers(
	UUIDSerializer::class,
	LocalDateTimeSerializer::class
)

package org.jellyfin.sdk.model.api

import java.time.LocalDateTime
import java.util.UUID
import kotlin.Boolean
import kotlin.String
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.UseSerializers
import org.jellyfin.sdk.model.serializer.LocalDateTimeSerializer
import org.jellyfin.sdk.model.serializer.UUIDSerializer

/**
 * Stores the state of an quick connect request.
 */
@Serializable
public data class QuickConnectResult(
	/**
	 * Gets a value indicating whether this request is authorized.
	 */
	@SerialName("Authenticated")
	public val authenticated: Boolean,
	/**
	 * Gets the secret value used to uniquely identify this request. Can be used to retrieve
	 * authentication information.
	 */
	@SerialName("Secret")
	public val secret: String,
	/**
	 * Gets the user facing code used so the user can quickly differentiate this request from others.
	 */
	@SerialName("Code")
	public val code: String,
	/**
	 * Gets or sets the private access token.
	 */
	@SerialName("Authentication")
	public val authentication: UUID? = null,
	/**
	 * Gets or sets the DateTime that this request was created.
	 */
	@SerialName("DateAdded")
	public val dateAdded: LocalDateTime
)
